### ISSUE TITLE
Profile inheritance?

### ISSUE THREAD

**Issue by mesgme** [alexpop/ssl-certificate-profile#2]
I'mrying to use the ssl_certificate profile.

I included it as a dependency in my main profile

Keep getting Skipping profile: 'ssl-certificate-profile' on unsupported platform: 'ubuntu/18.04'
Then undefined method `ssl_certificate' when I try to use the resource

Is there an obvious reason for this platform problem?
Do I need to do something to trigger downloading the dependencies?

Sorry I'm not a heavy user of Inspec so might have missed something.

**Comment by alexpop** [comment]
Thank you for raising this issue. I'll look into it and will let you know what I find.

**Comment by alexpop** [comment]
Hey, I apologize for not coming back to you on this.
I've recently revisited this repository and fixed the problem you reported.

I even created a profile that uses `inspec-ssl-certificate` as a resource pack: https://github.com/alexpop/audit-ssl

You can see a snippet of the execution below:
```bash
$ inspec exec https://github.com/alexpop/audit-ssl/archive/master.tar.gz

Profile: SSL Audit Profile (audit-ssl)
Version: 0.2.0
Target:  local://

  ✔  01-ssl-exists: Check that all sites return an SSL certificate
     ✔  ssl_certificate for 'chef.io' is expected to exist
     ✔  ssl_certificate for 'docs.chef.io' is expected to exist
     ✔  ssl_certificate for 'blog.chef.io' is expected to exist
     ✔  ssl_certificate for 'learn.chef.io' is expected to exist
```

**Comment by mesgme** [comment]
Thanks for getting back to me.  Can you post a link to the commit / changed file so I can see what the fix was?

**Comment by alexpop** [comment]
It was this `supports` yml option: https://github.com/alexpop/inspec-ssl-certificate/commit/b98eb67ea57c50a0f9352b51a3e271834a2702cd

**Comment by alexpop** [comment]
I'm closing the ticket, thanks again!
